import { StyleSheet } from 'react-native';

export const splashScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 44,
    overflow: 'hidden',
  },
  waveBack: {
    position: 'absolute',
    bottom: -38,
    width: '128%',
    height: 132,
    borderRadius: 66,
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  waveFront: {
    position: 'absolute',
    bottom: -72,
    width: '138%',
    height: 154,
    borderRadius: 77,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  bubbleLarge: {
    position: 'absolute',
    top: '23%',
    right: '18%',
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.45)',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  bubbleSmall: {
    position: 'absolute',
    top: '34%',
    left: '23%',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.28)',
  },
  logoWrap: {
    width: 176,
    height: 176,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo: {
    width: 160,
    height: 160,
  },
  textBlock: {
    alignItems: 'center',
    marginTop: 6,
  },
  title: {
    fontSize: 36,
    color: '#FFFFFF',
    fontWeight: '800',
    letterSpacing: 0,
    textShadowColor: 'rgba(20,70,110,0.18)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  subtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.84)',
    fontWeight: '600',
    letterSpacing: 0,
    marginTop: 6,
  },
  dotsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 30,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#FFFFFF',
  },
});
